### ISSUE TITLE
Exception on pseudo-image upload

### ISSUE THREAD

**Issue by Fak3** [riklaunim/django-ckeditor#46]
When i upload this sample file [1] with image upload dialog - i got exception on server. Upload interface because of exception does not give any informative error message.

The file is image renamed to .doc.
[1] - https://yadi.sk/i/j7c35vXKZHad3

```
127.0.0.1 - - [08/Aug/2014 15:49:10] "POST /en/ckeditor/upload/?CKEditor=id_grounds_en&CKEditorFuncNum=0&langCode=en HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/u1/.virtualenvs/exmo/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 72, in __call__
return self.application(environ, start_response)
  File "/home/u1/.virtualenvs/exmo/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 255, in __call__
    response = self.get_response(request)
  File "/home/u1/.virtualenvs/exmo/lib/python2.7/site-packages/django/core/handlers/base.py", line 178, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/u1/.virtualenvs/exmo/lib/python2.7/site-packages/django/core/handlers/base.py", line 217, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/u1/.virtualenvs/exmo/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 5, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/home/u1/.virtualenvs/exmo/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/u1/.virtualenvs/exmo/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/u1/.virtualenvs/exmo/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/z/pproj/exmo2010/exmo/exmo2010/views.py", line 248, in ckeditor_upload
    return upload(request)
  File "/home/u1/.virtualenvs/exmo/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/u1/.virtualenvs/exmo/lib/python2.7/site-packages/ckeditor/views.py", line 62, in upload
    backend.create_thumbnail(saved_path)
  File "/home/u1/.virtualenvs/exmo/lib/python2.7/site-packages/ckeditor/image/pillow_backend.py", line 38, in create_thumbnail
    imagefit.save(thumbnail_io, format=file_format)
  File "/home/u1/.virtualenvs/exmo/lib/python2.7/site-packages/PIL/Image.py", line 1456, in save
    save_handler = SAVE[format.upper()] # unknown format
KeyError: 'MSWORD'
```

**Comment by riklaunim** [comment]
Maybe django_extensions added something to this. I'll check.
