### ISSUE TITLE
Collectstatic don't works with .egg

### ISSUE THREAD

**Issue by SalahAdDin** [riklaunim/django-ckeditor#53]
Hi, i'm install ckeditor in my webserver and him install all packages as a .eggs, when i do manage.py collectstatic, don't take any ckeditor's static files and this make ma an error in the server, what can i do?

Then i have this

```
Internal Server Error: /admin/news/new/97/
Traceback (most recent call last):
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/core/handlers/base.py", line 137, in get_response
response = response.render()
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/response.py", line 103, in render
self.content = self.rendered_content
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/response.py", line 80, in rendered_content
content = template.render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/base.py", line 148, in render
return self._render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/base.py", line 142, in _render
return self.nodelist.render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/base.py", line 844, in render
bit = self.render_node(node, context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/debug.py", line 80, in render_node
return node.render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/loader_tags.py", line 126, in render
return compiled_parent._render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/base.py", line 142, in _render
return self.nodelist.render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/base.py", line 844, in render
bit = self.render_node(node, context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/debug.py", line 80, in render_node
return node.render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/loader_tags.py", line 126, in render
return compiled_parent._render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/base.py", line 142, in _render
return self.nodelist.render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/base.py", line 844, in render
bit = self.render_node(node, context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/debug.py", line 80, in render_node
return node.render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/loader_tags.py", line 65, in render
result = block.nodelist.render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/base.py", line 844, in render
bit = self.render_node(node, context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/debug.py", line 80, in render_node
return node.render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/loader_tags.py", line 65, in render
result = block.nodelist.render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/base.py", line 844, in render
bit = self.render_node(node, context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/debug.py", line 80, in render_node
return node.render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/loader_tags.py", line 65, in render
result = block.nodelist.render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/base.py", line 844, in render
bit = self.render_node(node, context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/debug.py", line 80, in render_node
return node.render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/loader_tags.py", line 65, in render
result = block.nodelist.render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/base.py", line 844, in render
bit = self.render_node(node, context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/debug.py", line 80, in render_node
return node.render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/defaulttags.py", line 201, in render
nodelist.append(node.render(context))
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/loader_tags.py", line 150, in render
return template.render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/base.py", line 148, in render
return self._render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/base.py", line 142, in _render
return self.nodelist.render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/base.py", line 844, in render
bit = self.render_node(node, context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/debug.py", line 80, in render_node
return node.render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/defaulttags.py", line 201, in render
nodelist.append(node.render(context))
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/defaulttags.py", line 527, in render
return self.nodelist.render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/base.py", line 844, in render
bit = self.render_node(node, context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/debug.py", line 80, in render_node
return node.render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/defaulttags.py", line 201, in render
nodelist.append(node.render(context))
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/defaulttags.py", line 402, in render
return strip_spaces_between_tags(self.nodelist.render(context).strip())
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/base.py", line 844, in render
bit = self.render_node(node, context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/debug.py", line 80, in render_node
return node.render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/defaulttags.py", line 312, in render
return nodelist.render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/base.py", line 844, in render
bit = self.render_node(node, context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/debug.py", line 80, in render_node
return node.render(context)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/debug.py", line 93, in render
output = force_text(output)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/utils/encoding.py", line 83, in force_text
s = six.text_type(s)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/forms/forms.py", line 508, in __str__
return self.as_widget()
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/forms/forms.py", line 560, in as_widget
return force_text(widget.render(name, self.value(), attrs=attrs))
File "/home/salahaddinal/lib/python3.4/django_ckeditor_updated-4.4.0-py3.4.egg/ckeditor/widgets.py", line 100, in render
'external_plugin_resources' : self.external_plugin_resources
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/loader.py", line 170, in render_to_string
t = get_template(template_name, dirs)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/loader.py", line 144, in get_template
template, origin = find_template(template_name, dirs)
File "/home/salahaddinal/webapps/tiempoturco/lib/python3.4/django/template/loader.py", line 136, in find_template
raise TemplateDoesNotExist(name)
django.template.base.TemplateDoesNotExist: ckeditor/widget.html

```

and my configurations is it:

``` python
INSTALLED_APPS = (
    #'grappelli.dashboard',
    #'grappelli',
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'django_extensions',
    'embed_video',
    'import_export',
    'permission',
    'rest_framework',
    'social.apps.django_app.default',
    'sorl.thumbnail',
    'authors',
    'gallery',
    'images',
    'keywords',
    'news',
    'subtopic',
    'topic',
    'videos',
)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

#if DEBUG:
    #MEDIA_ROOT = os.sep.join(os.path.abspath(__file__).split(os.sep)[:-2] + ['statics/media'])
MEDIA_ROOT = '/home/.../tiempoturco_static/media'
    #STATIC_ROOT = os.sep.join(os.path.abspath(__file__).split(os.sep)[:-2] + ['statics/static_only'])
STATIC_ROOT = '/home/.../tiempoturco_static/static'
    #STATICFILES_DIRS = os.sep.join(os.path.abspath(__file__).split(os.sep)[:-2] + ['statics/static'])
STATICFILES_DIRS = (os.path.join(os.path.dirname(BASE_DIR), "tiempoturco", "statics", "static"),)

MEDIA_URL = '/static/media/'
STATIC_URL = '/static/static/'

TEMPLATE_DIRS = (
    #os.path.abspath(__file__).split(os.sep)[:-2] + ['static/templates']
    os.path.join(os.path.dirname(BASE_DIR), "tiempoturco", "statics", "templates"),
)

#CKEditor Options
CKEDITOR_UPLOAD_PATH = "/home/.../tiempoturco_static/media/uploads"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'null',
        'width': 650,
        'language': 'es',
        'toolbarCanCollapse' : 'true',
    },
}

```

**Comment by SalahAdDin** [comment]
Hey men, is very important, my web site is in production,
